### PR TITLE
Fix all warning generated by cargo clippy, and auto format it.

### PR DESCRIPTION
**Pull request by HsuJv**
Hi there,

Actually, I'd like to build an ssh wasm application and found this crate, which is closest to what I need
But the problem is that wasm needs a websocket and in order not to break the existing logic, it needs to be asynchronous.
So I'm going to change this
```Rust
pub struct Client {
    pub(crate) stream: TcpStream,
    pub(crate) sequence: Sequence,
    pub(crate) timeout: Timeout,
    pub(crate) encryption: Option<Box<dyn Encryption>>,
    pub(crate) is_encryption: bool,
    pub(crate) session_id: Vec<u8>,
}
```
To 
```Rust
use tokio::io::{AsyncRead, AsyncWrite};

pub struct Client<S> 
where
    S: AsyncRead + AsyncWrite + Unpin,
{
    pub(crate) stream: S,
    pub(crate) sequence: Sequence,
    pub(crate) timeout: Timeout,
    pub(crate) encryption: Option<Box<dyn Encryption>>,
    pub(crate) is_encryption: bool,
    pub(crate) session_id: Vec<u8>,
}
```

Just like my own crate [vnc-rs](https://crates.io/crates/vnc-rs) does

But these changes seemed huge, so I decided to start with cargo clippy & fmt on the existing code while getting the tests for cargo all successful.

As fmt can be a real turn-off for code reviews, I made a separate commit of fmt and the other containing just the clippy results.
Hope this is helpful to you.

```Bash
$ cargo clippy --fix
    Checking ssh-rs v0.2.1 (/home/my/projects/ssh-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 1.77s
$ cargo test
   Compiling ssh-rs v0.2.1 (/home/my/projects/ssh-rs)
    Finished test [unoptimized + debuginfo] target(s) in 0.78s
     Running unittests src/lib.rs (target/debug/deps/ssh_rs-bd2d7b9dabb611b3)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests ssh-rs

running 8 tests
test src/lib.rs - (line 9) - compile ... ok
test src/lib.rs - (line 49) - compile ... ok
test src/lib.rs - (line 33) - compile ... ok
test src/lib.rs - (line 21) - compile ... ok
test src/lib.rs - (line 137) - compile ... ok
test src/lib.rs - (line 103) - compile ... ok
test src/lib.rs - (line 84) - compile ... ok
test src/lib.rs - (line 65) - compile ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s
```

BRs

### CODE REVIEW

**Comment by 1148118271** [comment]
Ok, I have merged the code. In addition, I may have some code submissions about other issues in the past few days. When you follow up on the asynchronous issues, remember to check whether the code in the main branch is up to date.

**Comment by HsuJv** [comment]
Sure, will keep it in mind.

One more question, why did you put [workspace] in the Cargo.toml?
https://github.com/1148118271/ssh-rs/blob/7ca550e05793d76109c2b4a00857ce18873580d5/Cargo.toml#L14-L16
 I think cargo itself has an integration test when it finds the `/tests` folder in the project root. Explicitly putting it into a workspace doesn't seem to be very useful.

Is it okay for [my following commit](https://github.com/HsuJv/ssh-rs/commit/95ed9138440bb424dbdcb46fa5907ec8900cffd1) to delete this?

**Comment by 1148118271** [comment]
Of course, you can always delete this folder in future commits.

**Comment by 1148118271** [comment]
Of course, you can always delete this folder in future commits.

**Pull request merged**
