### PR TITLE
Ver 0.3 

### PR DESCRIPTION
**Pull request by HsuJv**
Just open here for further review.

Main changes:
1. Use session builder to build ssh session, which
gives the customer opportunities to config their own preferred algorithms
to connect to the specified ssh server.
2. Disable ssh-rsa by default
3. Make the ssh connection can fallback from public key authentication to password authentication, which keeps the same as OpenSSH.
4. refactor and re-folder the main code
5. multi-thread architecture supports

### CODE REVIEW

**Comment by HsuJv** [comment]
No rush to resolve conflicts for now

**Comment by HsuJv** [comment]
我们大约加一下qq或微信来大致共享一下进度？另外这个不着急pr合哈，还得再改改

**Comment by 1148118271** [comment]
可以加个微信或者qq的,在这上面交流太不方便了😂，13964019534 我手机号，应该可以直接加到我的微信，1148118271 我qq 看你方便加哪个都行。

**Comment by 1148118271** [comment]
那我先不合了，下班下班。

**Pull request merged**
