### PR TITLE
Implementation of Deprecated DSS PubKey

### PR DESCRIPTION
**Pull request by cchance27**
Not sure if your accepting PR's but I went ahead and implemented the SSH-DSS pubkey algorithm, tried to follow your pattern and naming conventions as best as I could. 

Have tested it locally connecting to a local device that only supports DSS, as well as some other algorithms that are deprecated but already supported. 

Implemented after running into it with #80

### CODE REVIEW

**Comment by HsuJv** [comment]
LGTM, thanks for the contribution,
But if you could help fix the CI warnings so that I can merge 'em into the main?

BRs.

Note:
`ssh-dss` should be added for both `HostKeyAlgorithms` & `PubkeyAcceptedAlgorithms` in this line

https://github.com/1148118271/ssh-rs/blob/040bcf9cee233387dea9405efa67635c9558cafd/.github/workflows/build.yml#L87

**Comment by cchance27** [comment]
cleaned up the cargo fmt and clippy warnings, and adjusted the CI params should clear now.

**Comment by HsuJv** [comment]
Close #80

**Comment by HsuJv** [comment]
Seems we cannot simply configure the server to use `ssh-dss` like `ssh-rsa`, which looks strange.
I'll have another release when I manage to fix the CI issue.

BRs.

**Comment by HsuJv** [comment]
version `0.4.3` is now released

Thanks again for the contribution.

**Pull request merged**
