### PR TITLE
Bump dependencies + clippy warnings

### PR DESCRIPTION
**Pull request by r3dlight**
* Bump ssh-key & ed25519-dalek dependencies (security fix)
* Bump rsa, signature, strum-macros, strum and ring crates
 * Fix some really quick clippy warnings

### CODE REVIEW

**Comment by HsuJv** [comment]
Hi, I don't know if it's convenient for you to fix these workflow errors, if not I can take a look at them this weekend.

**Comment by r3dlight** [comment]
Hum not sure I can fix these two "public_key" and "key_exchange" mutability warnings without breaking more things...

**Comment by HsuJv** [comment]
Never mind, I can take a look this weekend. :-)

**Comment by r3dlight** [comment]
Great thank you :-)

**Comment by HsuJv** [comment]
Hi @r3dlight ,

I've done with the workflow fixes and also bumped the `aes` crate to 0.8
Please process the PR in your repo so that I can merge this PR.

BRs.

**Comment by r3dlight** [comment]
Hi [HsuJv](https://github.com/HsuJv),

Great, merged, thanks for the patch :)

**Comment by HsuJv** [comment]
This closes #70

**Comment by HsuJv** [comment]
v0.3.3 has been published

**Pull request merged**
